version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 8883:8883
    volumes:
      - ./services/backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8883
  
  # frontend:
  #   build: ./services/frontend
  #   volumes:
  #     - './services/frontend:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 8882:8080